# Generated by Django 2.1.7 on 2019-03-29 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercreation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskcreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=20)),
                ('taskleader', models.BooleanField(default=False)),
                ('tasklug', models.SlugField(blank=True)),
                ('taskdescription', models.TextField(blank=True)),
                ('taskassignee', models.CharField(blank=True, max_length=255)),
                ('taskstatus', models.CharField(default=None, max_length=40)),
                ('taskteamname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamtaskname', to='usercreation.Teamcreation')),
                ('taskuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
