# Generated by Django 2.1.7 on 2019-03-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcreation',
            old_name='tasklug',
            new_name='taskslug',
        ),
    ]
