# Generated by Django 2.1.7 on 2019-03-30 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20190330_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True)),
                ('commentteamname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentteamname', to='task.Taskcreation')),
                ('commentuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
