# Generated by Django 2.1.7 on 2019-03-29 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamcreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('teamleader', models.BooleanField(default=False)),
                ('teamslug', models.SlugField(blank=True)),
                ('teamuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
